import type { Metadata } from "next";
import { getServerLocale, pickByLocale } from "@/lib/locale-server";

export const metadata: Metadata = {
  title: "콘텐츠 운영 원칙 | Eat & Run",
  description: "Eat & Run의 콘텐츠 제작 기준, 광고 노출 기준, 품질 관리 원칙을 안내합니다."
};

export default async function EditorialPolicyPage() {
  const locale = await getServerLocale();
  const t = (ko: string, en: string) => pickByLocale(locale, ko, en);

  return (
    <main className="app-shell">
      <section className="glass-card space-y-6">
        <header className="space-y-3">
          <h1 className="text-2xl font-bold text-white sm:text-3xl">
            {t("콘텐츠 및 광고 운영 원칙", "Content and Ads Policy")}
          </h1>
          <p className="text-sm leading-relaxed text-zinc-300">
            {t(
              "Eat & Run은 사용자에게 유익한 건강 루틴 정보를 우선하며, 광고는 콘텐츠를 대체하지 않고 보조하는 수준에서 운영합니다.",
              "Eat & Run prioritizes useful health routine information, and ads are operated only as support, not as content replacement."
            )}
          </p>
        </header>

        <article className="space-y-2">
          <h2 className="text-lg font-semibold text-white">{t("1. 중복/저품질 콘텐츠 지양", "1. No duplicate/low-quality content")}</h2>
          <p className="text-sm leading-relaxed text-zinc-300">
            {t(
              "동일한 내용을 반복하는 페이지를 대량 생성하지 않으며, 자동 생성 문서만으로 구성된 페이지를 운영하지 않습니다. 모든 핵심 페이지는 사용자 행동에 도움이 되는 목적을 갖습니다.",
              "We do not mass-produce repetitive pages and do not run pages made only of autogenerated text. Every core page exists to help user action."
            )}
          </p>
        </article>

        <article className="space-y-2">
          <h2 className="text-lg font-semibold text-white">{t("2. 사용자 중심 탐색 구조", "2. User-centered navigation")}</h2>
          <p className="text-sm leading-relaxed text-zinc-300">
            {t(
              "사용자가 필요한 정보에 빠르게 도달할 수 있도록 명확한 내비게이션과 정책 페이지 링크를 제공합니다.",
              "We provide clear navigation and policy links so users can reach what they need quickly."
            )}
          </p>
        </article>

        <article className="space-y-2">
          <h2 className="text-lg font-semibold text-white">{t("3. 광고와 콘텐츠의 균형", "3. Balance between ads and content")}</h2>
          <p className="text-sm leading-relaxed text-zinc-300">
            {t(
              "광고는 콘텐츠보다 과도하게 눈에 띄지 않도록 배치하며, 본문이 거의 없는 페이지나 오류 페이지에 광고를 우선적으로 배치하지 않습니다.",
              "Ads are placed so they do not overpower content. We do not prioritize ads on thin-content pages or error pages."
            )}
          </p>
        </article>

        <article className="space-y-2">
          <h2 className="text-lg font-semibold text-white">{t("4. 신뢰성과 투명성", "4. Trust and transparency")}</h2>
          <p className="text-sm leading-relaxed text-zinc-300">
            {t(
              "서비스 소개, 이용약관, 개인정보처리방침, 문의 채널을 상시 공개합니다. 사용자에게 약속한 기능과 정보를 실제 서비스에서 일관되게 제공합니다.",
              "We keep About, Terms, Privacy, and Contact channels always visible, and deliver promised features and information consistently."
            )}
          </p>
        </article>
      </section>
    </main>
  );
}

